import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import type {
  SnapshotIssueState,
  SnapshotPlanState,
  SnapshotTaskState,
} from "../../domain/snapshot.js";

/**
 * Issues table schema
 *
 * Uses hybrid approach:
 * - Scalar fields (id, number, title, type, priority, status) as standard SQLite columns (indexed, queryable)
 * - Array/nested fields (acceptanceCriteria, labels) as JSON columns (flexible, type-safe)
 */
export const issues = sqliteTable("issues", {
  // Primary key and unique identifier
  id: text("id").primaryKey(),

  // Auto-incrementing issue number (e.g., #1, #2, #3)
  number: integer("number").notNull().unique(),

  // Core issue fields
  title: text("title").notNull(),
  description: text("description").notNull(),
  type: text("type").notNull(), // 'FEATURE' | 'BUG' | 'ENHANCEMENT' | 'TASK'
  priority: text("priority").notNull(), // 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
  status: text("status").notNull(), // 'OPEN' | 'IN_PROGRESS' | 'CLOSED'

  // JSON columns for arrays (flexible, auto-serialized by Drizzle)
  acceptanceCriteria: text("acceptance_criteria", { mode: "json" })
    .$type<string[]>()
    .notNull()
    .default(sql`'[]'`),

  labels: text("labels", { mode: "json" })
    .$type<string[]>()
    .notNull()
    .default(sql`'[]'`),

  // Optional metadata fields
  templateUsed: text("template_used"),
  createdBy: text("created_by"),

  // Timestamps (stored as ISO strings)
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

/**
 * Snapshots table schema
 *
 * Groups issue+plan+tasks into versioned snapshots for complete version tracking.
 */
export const snapshots = sqliteTable("snapshots", {
  // Primary key
  id: text("id").primaryKey(),

  // Link to issue number (not id, for easier querying)
  issueNumber: integer("issue_number").notNull(),

  // Version tracking
  version: integer("version").notNull(),
  status: text("status").notNull(), // 'ACTIVE' | 'ARCHIVED'
  snapshotType: text("snapshot_type").notNull(), // 'MANUAL' | 'ISSUE_UPDATE' | 'PLAN_REGENERATION'

  // Complete state capture (JSON blobs)
  issueState: text("issue_state", { mode: "json" })
    .$type<SnapshotIssueState>()
    .notNull(),
  planState: text("plan_state", { mode: "json" }).$type<SnapshotPlanState | null>(),
  tasksState: text("tasks_state", { mode: "json" })
    .$type<SnapshotTaskState[]>()
    .notNull()
    .default(sql`'[]'`),

  // Metadata
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull(),
  notes: text("notes"),
});

/**
 * Plans table schema
 *
 * Implementation plans for issues with approach and complexity estimation.
 */
export const plans = sqliteTable("plans", {
  // Primary key
  id: text("id").primaryKey(),

  // Foreign key - one plan per issue
  issueId: text("issue_id")
    .notNull()
    .references(() => issues.id, { onDelete: "cascade" }),

  // Plan content
  summary: text("summary").notNull(),
  approach: text("approach").notNull(), // Markdown content
  estimatedComplexity: text("estimated_complexity").notNull(), // 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH'

  // Metadata
  generatedBy: text("generated_by").notNull(),

  // Timestamps
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

/**
 * Tasks table schema
 *
 * Individual implementation steps within a plan with status tracking.
 */
export const tasks = sqliteTable("tasks", {
  // Primary key
  id: text("id").primaryKey(),

  // Foreign key
  planId: text("plan_id")
    .notNull()
    .references(() => plans.id, { onDelete: "cascade" }),

  // Ordering and content
  order: integer("order").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  status: text("status").notNull(), // 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'ABANDONED'

  // Task source - generated by AI or manually created
  source: text("source").notNull().default("generated"), // 'generated' | 'manual'

  // JSON column for acceptance criteria
  acceptanceCriteria: text("acceptance_criteria", { mode: "json" })
    .$type<string[]>()
    .notNull()
    .default(sql`'[]'`),

  // Optional fields
  estimatedMinutes: integer("estimated_minutes"),

  // Soft delete support
  isDeleted: integer("is_deleted", { mode: "boolean" }).notNull().default(false),
  deletedAt: text("deleted_at"),
  deletedBy: text("deleted_by"),

  // Smart matching tracking
  matchedFromTaskId: text("matched_from_task_id"),
  matchConfidence: real("match_confidence"),

  // Session tracking (mutable fields)
  sessionId: text("session_id"),
  sessionStartedAt: text("session_started_at"),
  lastSessionActivityAt: text("last_session_activity_at"),

  // Skill labels (references .track/skills/<label>.md files)
  labels: text("labels", { mode: "json" })
    .$type<string[]>()
    .default(sql`'[]'`),

  // Subagent execution context
  contextInstructions: text("context_instructions"),

  // Status timestamps
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  abandonedAt: text("abandoned_at"),

  // Record timestamps
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

/**
 * Task status history table schema
 *
 * Audit trail for task status changes without creating full snapshots.
 */
export const taskStatusHistory = sqliteTable("task_status_history", {
  // Primary key
  id: text("id").primaryKey(),

  // Foreign key to task
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),

  // Status transition
  fromStatus: text("from_status").notNull(),
  toStatus: text("to_status").notNull(),

  // Metadata
  changedBy: text("changed_by"),
  changedAt: text("changed_at").notNull(),
  notes: text("notes"),

  // Session tracking
  sessionId: text("session_id"),
});

/**
 * Task execution logs table schema
 *
 * Records progress during subagent execution for audit trail.
 * Subagents call log_task_progress to record what they're doing,
 * and the main session can retrieve these logs after completion.
 */
export const taskExecutionLogs = sqliteTable("task_execution_logs", {
  // Primary key
  id: text("id").primaryKey(),

  // Foreign key to task
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),

  // Session that logged this entry
  sessionId: text("session_id").notNull(),

  // Log content
  message: text("message").notNull(),

  // Optional list of files modified
  filesModified: text("files_modified", { mode: "json" }).$type<string[]>(),

  // Timestamp
  createdAt: text("created_at").notNull(),
});

// Type inference for SELECT operations
export type IssueRow = typeof issues.$inferSelect;
export type SnapshotRow = typeof snapshots.$inferSelect;
export type PlanRow = typeof plans.$inferSelect;
export type TaskRow = typeof tasks.$inferSelect;
export type TaskStatusHistoryRow = typeof taskStatusHistory.$inferSelect;
export type TaskExecutionLogRow = typeof taskExecutionLogs.$inferSelect;

// Type inference for INSERT operations
export type NewIssue = typeof issues.$inferInsert;
export type NewSnapshot = typeof snapshots.$inferInsert;
export type NewPlan = typeof plans.$inferInsert;
export type NewTask = typeof tasks.$inferInsert;
export type NewTaskStatusHistory = typeof taskStatusHistory.$inferInsert;
export type NewTaskExecutionLog = typeof taskExecutionLogs.$inferInsert;
