/**
 * Worker Queue Database Schema
 *
 * Separate database for worker/queue infrastructure.
 * Lives at ~/.track/worker-queue.db
 *
 * This separates execution concerns from tracking concerns:
 * - workflow.db: issues, tasks, plans, projects (domain)
 * - worker-queue.db: workers, dispatch queue (infrastructure)
 */

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

/**
 * Workers table schema
 *
 * Tracks active Claude worker processes for the worker pool feature.
 * Workers self-register, send heartbeats, and claim tasks from dispatch_queue.
 */
export const workers = sqliteTable("workers", {
  // Primary key (UUID generated by worker on startup)
  id: text("id").primaryKey(),

  // Human-friendly name (e.g., "worker-1", "macbook-pro")
  name: text("name").notNull(),

  // Worker status
  // IDLE: waiting for task assignment
  // WORKING: actively executing a task
  // DRAINING: will exit after current task completes (graceful shutdown)
  status: text("status").notNull().default("IDLE"), // 'IDLE' | 'WORKING' | 'DRAINING'

  // Heartbeat timestamp - updated periodically to prove worker is alive
  // Workers with stale heartbeats (>10s) are considered dead
  lastHeartbeat: text("last_heartbeat").notNull(),

  // Process ID of the worker process - used to kill stale workers before reclaiming tasks
  pid: integer("pid"),

  // Timestamps
  createdAt: text("created_at").notNull(),
});

/**
 * Dispatch queue table schema
 *
 * Queue of tasks assigned to workers.
 * Workers poll this queue and atomically claim unclaimed or stale-claimed tasks.
 *
 * Flow:
 * 1. dispatch_task(taskId, projectSlug) → INSERT with status=PENDING
 * 2. Worker polls → finds PENDING or stale WORKING task
 * 3. Worker claims → UPDATE status=WORKING, worker_id, claimed_at
 * 4. Task reaches terminal state → DELETE from queue
 *
 * The projectSlug is the bridge to the tracking database:
 * - Worker claims task → gets (taskId, projectSlug)
 * - Uses ProjectsResolver.getProjectBySlug(projectSlug) → sourceInfo, gitRoot
 * - Connects to tracking db and spawns Claude in gitRoot
 */
export const dispatchQueue = sqliteTable("dispatch_queue", {
  // Task being dispatched (references tasks.id in workflow.db)
  taskId: text("task_id").primaryKey(),

  // Project slug - bridge to tracking database
  // Used to resolve sourceInfo (connection string) and gitRoot
  projectSlug: text("project_slug").notNull(),

  // Queue entry status: PENDING (unclaimed) or WORKING (claimed)
  status: text("status").notNull().default("PENDING"),

  // Worker that claimed this task (null = PENDING)
  workerId: text("worker_id"),

  // When the task was claimed (null = PENDING)
  claimedAt: text("claimed_at"),

  // When the task was added to the queue
  createdAt: text("created_at").notNull(),

  // Flag set by Claude via end_worker_session to signal it's done
  // Workers poll for this flag before terminating
  claudeDone: integer("claude_done", { mode: "boolean" }).notNull().default(false),

  // Timestamp when claudeDone was set (for timeout calculations)
  claudeDoneAt: text("claude_done_at"),
});

// Type inference for SELECT operations
export type WorkerRow = typeof workers.$inferSelect;
export type DispatchQueueRow = typeof dispatchQueue.$inferSelect;

// Type inference for INSERT operations
export type NewWorker = typeof workers.$inferInsert;
export type NewDispatchQueueEntry = typeof dispatchQueue.$inferInsert;
