/**
 * WorkerQueueDb - Domain interface for worker queue infrastructure
 *
 * Separates worker/queue concerns from the main tracking database.
 * This is infrastructure for task execution, not domain tracking.
 *
 * Lives at ~/.track/worker-queue.db (separate from workflow.db)
 */

import type { Worker, WorkerWithHealth, WorkerStatus, QueueStats } from "./worker.js";
import { Service } from "@dev-workflow/effect";

// Re-export for convenience
export type { QueueStats };

/**
 * Worker summary for dispatch status (alive workers only)
 */
export interface WorkerSummary {
  readonly total: number;
  readonly idle: number;
  readonly working: number;
  readonly draining: number;
}

/**
 * Dispatch queue entry status
 */
export type QueueEntryStatus = "PENDING" | "WORKING";

/**
 * Dispatch queue entry
 *
 * Contains taskId and projectSlug - everything needed to work on a task.
 * The projectSlug is the bridge to the tracking database.
 */
export interface QueueEntry {
  readonly taskId: string;
  readonly projectSlug: string;
  readonly status: QueueEntryStatus;
  readonly workerId: string | null;
  readonly claimedAt: string | null;
  readonly createdAt: string;
  readonly claudeDone: boolean;
  readonly claudeDoneAt: string | null;
}

/**
 * Queue entry with health information
 */
export interface QueueEntryWithHealth extends QueueEntry {
  readonly isStale: boolean;
  readonly workerName: string | null;
}

/**
 * WorkerQueueDb - Interface for worker queue database operations
 *
 * Encapsulates both worker registration and dispatch queue in a single
 * abstraction. These are tightly coupled (staleness checks require
 * joining workers with queue entries).
 *
 * Implementation connects to ~/.track/worker-queue.db
 */
export interface WorkerQueueDb {
  // ===========================================================================
  // Lifecycle
  // ===========================================================================

  /**
   * Close the database connection
   */
  close(): void;

  // ===========================================================================
  // Worker Operations
  // ===========================================================================

  /**
   * Register a new worker
   *
   * @param id - Worker UUID (generated by worker process)
   * @param name - Human-friendly name
   * @param pid - Process ID (for killing stale workers)
   * @returns The registered worker
   */
  registerWorker(id: string, name: string, pid?: number): Worker;

  /**
   * Unregister a worker (remove from registry)
   */
  unregisterWorker(id: string): void;

  /**
   * Update worker heartbeat timestamp
   */
  updateHeartbeat(id: string, pid?: number): Worker | null;

  /**
   * Update worker status
   */
  updateStatus(id: string, status: WorkerStatus): Worker | null;

  /**
   * Find worker by ID
   */
  findWorkerById(id: string): Worker | null;

  /**
   * Find all workers with health information
   */
  findAllWorkersWithHealth(thresholdSeconds?: number): WorkerWithHealth[];

  /**
   * Get worker summary counts
   */
  getWorkerSummary(thresholdSeconds?: number): WorkerSummary;

  /**
   * Generate the next available worker name (worker-1, worker-2, etc.)
   */
  getNextWorkerName(): string;

  /**
   * Clean up dead workers (stale heartbeats)
   *
   * @returns Number of workers removed
   */
  cleanupDeadWorkers(thresholdSeconds?: number): number;

  // ===========================================================================
  // Queue Operations
  // ===========================================================================

  /**
   * Add a task to the dispatch queue
   *
   * @param taskId - Task UUID
   * @param projectSlug - Project slug (bridge to tracking db)
   * @returns Queue entry (new or existing if already queued)
   */
  enqueue(taskId: string, projectSlug: string): QueueEntry;

  /**
   * Atomically claim a task from the queue
   *
   * Finds an unclaimed or stale-claimed task and claims it for the worker.
   *
   * @param workerId - Worker claiming the task
   * @param thresholdSeconds - Staleness threshold
   * @returns Claimed entry (with projectSlug) or null if none available
   */
  claimTask(workerId: string, thresholdSeconds?: number): QueueEntry | null;

  /**
   * Remove a task from the queue
   *
   * Called when task reaches terminal state (COMPLETED/ABANDONED).
   */
  remove(taskId: string): void;

  /**
   * Update the stored project slug for a queue entry.
   *
   * Self-heals a poisoned row: a dispatch bug may have stamped a row with the
   * dispatching/claiming worker's home project rather than the task's true
   * owner. Once the owner is resolved authoritatively from the task, this
   * corrects the stored label so it stops lying.
   *
   * @param taskId - Task UUID whose queue entry to heal
   * @param projectSlug - The task's authoritative owning-project slug
   */
  updateProjectSlug(taskId: string, projectSlug: string): void;

  /**
   * Find queue entry by task ID
   */
  findByTaskId(taskId: string): QueueEntry | null;

  /**
   * Find claim by worker ID
   *
   * Used for worker resume after reconnect.
   */
  findClaimByWorker(workerId: string): QueueEntry | null;

  /**
   * Find all queue entries with health information
   */
  findAllEntriesWithHealth(thresholdSeconds?: number): QueueEntryWithHealth[];

  /**
   * Get queue statistics
   */
  getQueueStats(thresholdSeconds?: number): QueueStats;

  /**
   * Mark a queue entry as claudeDone
   *
   * Called by end_worker_session to signal Claude is done.
   * Workers poll for this flag before terminating.
   *
   * @param taskId - Task UUID
   * @param workerId - Worker UUID (must match the claiming worker)
   * @returns Updated entry or null if not found/mismatch
   */
  setClaudeDone(taskId: string, workerId: string): QueueEntry | null;
}

export class WorkerQueueDbTag extends Service<WorkerQueueDb>()("workerQueueDb") {}
