/**
 * Domain types for Worker entity and Dispatch Queue
 *
 * Workers are Claude Code processes running in worker mode that can
 * claim tasks from a dispatch queue. This enables parallel task execution
 * across multiple terminal sessions.
 */

/**
 * Worker status
 *
 * - IDLE: Waiting for task assignment
 * - WORKING: Actively executing a task
 * - DRAINING: Will exit after current task completes (graceful shutdown)
 */
export type WorkerStatus = "IDLE" | "WORKING" | "DRAINING";

/**
 * Worker entity
 *
 * Represents a Claude Code process running in worker mode.
 * Workers self-register on startup and send periodic heartbeats.
 *
 * Note: Workers are global (not project-scoped) since they can work on
 * tasks from any project in the dev-workflow installation.
 */
export interface Worker {
  readonly id: string; // UUID generated by worker on startup
  readonly name: string; // Human-friendly name (e.g., "worker-1", "macbook-pro")
  readonly status: WorkerStatus;
  readonly lastHeartbeat: string; // ISO datetime string
  readonly pid: number | null; // Process ID - used to kill stale workers before reclaiming tasks
  readonly createdAt: string; // ISO datetime string
}

/**
 * Worker with health information
 *
 * Extended worker info including computed health status.
 */
export interface WorkerWithHealth extends Worker {
  /** Whether the worker is considered alive (heartbeat within threshold) */
  readonly isAlive: boolean;
  /** Seconds since last heartbeat */
  readonly heartbeatAge: number;
  /** Current task ID if the worker has claimed a task */
  readonly currentTaskId: string | null;
}

/**
 * Dispatch queue entry status
 *
 * - PENDING: Task in queue, waiting to be claimed
 * - WORKING: Worker has claimed and is actively working
 *
 * Entry is deleted when task reaches terminal state (COMPLETED/ABANDONED).
 * If a worker dies (stale heartbeat), another worker can reclaim the task.
 */
export type DispatchQueueStatus = "PENDING" | "WORKING";

/**
 * Dispatch queue entry
 *
 * Represents a task in the dispatch queue.
 * Entry is deleted when task reaches terminal state (COMPLETED/ABANDONED).
 */
export interface DispatchQueueEntry {
  readonly taskId: string; // Task being dispatched
  readonly status: DispatchQueueStatus; // Queue entry status
  readonly workerId: string | null; // Worker that claimed (null = PENDING)
  readonly claimedAt: string | null; // When claimed (null = PENDING)
  readonly createdAt: string; // When added to queue
  readonly claudeDone: boolean; // True when Claude calls end_worker_session
  readonly claudeDoneAt: string | null; // When claudeDone was set
}

/**
 * Dispatch queue entry with worker health info
 *
 * Extended entry including computed staleness.
 */
export interface DispatchQueueEntryWithHealth extends DispatchQueueEntry {
  /** Whether the claim is stale (worker is dead) */
  readonly isStale: boolean;
  /** Worker name if claimed */
  readonly workerName: string | null;
}

/**
 * Default heartbeat threshold in seconds
 *
 * Workers with heartbeats older than this are considered dead.
 */
export const DEFAULT_HEARTBEAT_THRESHOLD_SECONDS = 10;

/**
 * Queue statistics
 */
export interface QueueStats {
  readonly total: number;
  readonly unclaimed: number;
  readonly claimed: number;
  readonly stale: number;
}

/**
 * Check if a worker is alive based on heartbeat timestamp
 *
 * @param lastHeartbeat - ISO datetime string of last heartbeat
 * @param thresholdSeconds - Maximum age in seconds (default: 60)
 * @param now - Current time for testing (default: new Date())
 * @returns true if worker is alive
 */
export function isWorkerAlive(
  lastHeartbeat: string,
  thresholdSeconds: number = DEFAULT_HEARTBEAT_THRESHOLD_SECONDS,
  now: Date = new Date()
): boolean {
  const heartbeatTime = new Date(lastHeartbeat).getTime();
  const currentTime = now.getTime();
  const ageSeconds = (currentTime - heartbeatTime) / 1000;
  // Use strict less than so threshold=0 means "instant death" for testing
  return ageSeconds < thresholdSeconds;
}

/**
 * Calculate heartbeat age in seconds
 *
 * @param lastHeartbeat - ISO datetime string of last heartbeat
 * @param now - Current time for testing (default: new Date())
 * @returns Age in seconds
 */
export function getHeartbeatAge(lastHeartbeat: string, now: Date = new Date()): number {
  const heartbeatTime = new Date(lastHeartbeat).getTime();
  const currentTime = now.getTime();
  return Math.round((currentTime - heartbeatTime) / 1000);
}

/**
 * Repository interface for Worker persistence
 */
export interface WorkerRepository {
  /**
   * Register a new worker
   *
   * @param id - Worker UUID (generated by worker process)
   * @param name - Human-friendly name
   * @param pid - Process ID (optional, for killing stale workers)
   * @returns The registered worker
   */
  register(id: string, name: string, pid?: number): Worker;

  /**
   * Unregister a worker (remove from registry)
   *
   * @param id - Worker UUID
   */
  unregister(id: string): void;

  /**
   * Update worker heartbeat timestamp
   *
   * @param id - Worker UUID
   * @param pid - Process ID (optional, updated alongside heartbeat)
   * @returns Updated worker or null if not found
   */
  updateHeartbeat(id: string, pid?: number): Worker | null;

  /**
   * Update worker status
   *
   * @param id - Worker UUID
   * @param status - New status
   * @returns Updated worker or null if not found
   */
  updateStatus(id: string, status: WorkerStatus): Worker | null;

  /**
   * Find worker by ID
   *
   * @param id - Worker UUID
   * @returns Worker or null if not found
   */
  findById(id: string): Worker | null;

  /**
   * Find all workers with health information
   *
   * @param thresholdSeconds - Heartbeat threshold for alive check
   * @returns Array of workers with health info
   */
  findAllWithHealth(thresholdSeconds?: number): WorkerWithHealth[];

  /**
   * Clean up dead workers (stale heartbeats)
   *
   * @param thresholdSeconds - Maximum heartbeat age
   * @returns Number of workers removed
   */
  cleanupDeadWorkers(thresholdSeconds?: number): number;

  /**
   * Generate the next available worker name
   *
   * Auto-generates names like "worker-1", "worker-2", etc.
   *
   * @returns Next available worker name
   */
  getNextWorkerName(): string;
}

/**
 * Repository interface for Dispatch Queue persistence
 */
export interface DispatchQueueRepository {
  /**
   * Add a task to the dispatch queue
   *
   * Idempotent - if task is already queued, returns existing entry.
   *
   * @param taskId - Task to dispatch
   * @returns Queue entry (new or existing)
   */
  enqueue(taskId: string): DispatchQueueEntry;

  /**
   * Atomically claim a task from the queue
   *
   * Finds an unclaimed or stale-claimed task and claims it for the worker.
   * Uses atomic UPDATE to prevent race conditions.
   *
   * @param workerId - Worker claiming the task
   * @param thresholdSeconds - Staleness threshold
   * @returns Claimed entry or null if none available
   */
  claimTask(workerId: string, thresholdSeconds?: number): DispatchQueueEntry | null;

  /**
   * Remove a task from the queue
   *
   * Called when task reaches terminal state (COMPLETED/ABANDONED).
   *
   * @param taskId - Task to remove
   */
  remove(taskId: string): void;

  /**
   * Find claim by worker ID
   *
   * Used for worker resume after reconnect.
   *
   * @param workerId - Worker UUID
   * @returns Queue entry or null if worker has no claim
   */
  findClaimByWorker(workerId: string): DispatchQueueEntry | null;

  /**
   * Find queue entry by task ID
   *
   * @param taskId - Task UUID
   * @returns Queue entry or null if not queued
   */
  findByTaskId(taskId: string): DispatchQueueEntry | null;

  /**
   * Find all queue entries with health information
   *
   * @param thresholdSeconds - Staleness threshold
   * @returns Array of entries with health info
   */
  findAllWithHealth(thresholdSeconds?: number): DispatchQueueEntryWithHealth[];

  /**
   * Count entries in the queue
   *
   * @returns Total entries, unclaimed count, and stale count
   */
  getQueueStats(thresholdSeconds?: number): QueueStats;

  /**
   * Mark a queue entry as claudeDone
   *
   * Called by end_worker_session MCP tool to signal Claude is done.
   * Workers poll for this flag before terminating.
   *
   * @param taskId - Task UUID
   * @param workerId - Worker UUID (must match the claiming worker)
   * @returns Updated entry or null if not found or workerId mismatch
   */
  setClaudeDone(taskId: string, workerId: string): DispatchQueueEntry | null;
}
