/**
 * Domain types for Worker entity and Dispatch Queue
 *
 * Workers are Claude Code processes running in worker mode that can
 * claim tasks from a dispatch queue. This enables parallel task execution
 * across multiple terminal sessions.
 */

/**
 * Worker status
 *
 * - IDLE: Waiting for task assignment
 * - WORKING: Actively executing a task
 * - DRAINING: Will exit after current task completes (graceful shutdown)
 */
export type WorkerStatus = "IDLE" | "WORKING" | "DRAINING";

/**
 * Worker entity
 *
 * Represents a Claude Code process running in worker mode.
 * Workers self-register on startup and send periodic heartbeats.
 *
 * Note: Workers are global (not project-scoped) since they can work on
 * tasks from any project in the dev-workflow installation.
 */
export interface Worker {
  readonly id: string; // UUID generated by worker on startup
  readonly name: string; // Human-friendly name (e.g., "worker-1", "macbook-pro")
  readonly status: WorkerStatus;
  readonly lastHeartbeat: string; // ISO datetime string
  readonly pid: number | null; // Process ID - used to kill stale workers before reclaiming tasks
  readonly createdAt: string; // ISO datetime string
}

/**
 * Worker with health information
 *
 * Extended worker info including computed health status.
 */
export interface WorkerWithHealth extends Worker {
  /** Whether the worker is considered alive (heartbeat within threshold) */
  readonly isAlive: boolean;
  /** Seconds since last heartbeat */
  readonly heartbeatAge: number;
  /** Current task ID if the worker has claimed a task */
  readonly currentTaskId: string | null;
}

/**
 * Dispatch queue entry status
 *
 * - PENDING: Task in queue, waiting to be claimed
 * - WORKING: Worker has claimed and is actively working
 *
 * Entry is deleted when task reaches terminal state (COMPLETED/ABANDONED).
 * If a worker dies (stale heartbeat), another worker can reclaim the task.
 */
export type DispatchQueueStatus = "PENDING" | "WORKING";

/**
 * Dispatch queue entry
 *
 * Represents a task in the dispatch queue.
 * Entry is deleted when task reaches terminal state (COMPLETED/ABANDONED).
 */
export interface DispatchQueueEntry {
  readonly taskId: string; // Task being dispatched
  readonly status: DispatchQueueStatus; // Queue entry status
  readonly workerId: string | null; // Worker that claimed (null = PENDING)
  readonly claimedAt: string | null; // When claimed (null = PENDING)
  readonly createdAt: string; // When added to queue
  readonly claudeDone: boolean; // True when Claude calls end_worker_session
  readonly claudeDoneAt: string | null; // When claudeDone was set
}

/**
 * Dispatch queue entry with worker health info
 *
 * Extended entry including computed staleness.
 */
export interface DispatchQueueEntryWithHealth extends DispatchQueueEntry {
  /** Whether the claim is stale (worker is dead) */
  readonly isStale: boolean;
  /** Worker name if claimed */
  readonly workerName: string | null;
}

/**
 * Default heartbeat threshold in seconds
 *
 * Workers with heartbeats older than this are considered dead.
 */
export const DEFAULT_HEARTBEAT_THRESHOLD_SECONDS = 10;

/**
 * Queue statistics
 */
export interface QueueStats {
  readonly total: number;
  readonly unclaimed: number;
  readonly claimed: number;
  readonly stale: number;
}

/**
 * Check if a worker is alive based on heartbeat timestamp
 *
 * @param lastHeartbeat - ISO datetime string of last heartbeat
 * @param thresholdSeconds - Maximum age in seconds (default: 60)
 * @param now - Current time for testing (default: new Date())
 * @returns true if worker is alive
 */
export function isWorkerAlive(
  lastHeartbeat: string,
  thresholdSeconds: number = DEFAULT_HEARTBEAT_THRESHOLD_SECONDS,
  now: Date = new Date()
): boolean {
  const heartbeatTime = new Date(lastHeartbeat).getTime();
  const currentTime = now.getTime();
  const ageSeconds = (currentTime - heartbeatTime) / 1000;
  // Use strict less than so threshold=0 means "instant death" for testing
  return ageSeconds < thresholdSeconds;
}

/**
 * Calculate heartbeat age in seconds
 *
 * @param lastHeartbeat - ISO datetime string of last heartbeat
 * @param now - Current time for testing (default: new Date())
 * @returns Age in seconds
 */
export function getHeartbeatAge(lastHeartbeat: string, now: Date = new Date()): number {
  const heartbeatTime = new Date(lastHeartbeat).getTime();
  const currentTime = now.getTime();
  return Math.round((currentTime - heartbeatTime) / 1000);
}
