import type { Issue } from "@dev-workflow/mcp-server/domain/issue.js";
import type { Plan } from "@dev-workflow/mcp-server/domain/plan.js";
import type { Task } from "@dev-workflow/mcp-server/domain/task.js";
import { escapeHtml } from "./layout.js";

export interface IssueDetailData {
  issue: Issue;
  plan?: Plan;
  tasks?: Task[];
  activeTab?: "details" | "plan" | "tasks";
}

export function renderIssueDetail(data: IssueDetailData): string {
  const { issue, plan, tasks = [], activeTab = "details" } = data;

  const taskCounts = {
    total: tasks.length,
    completed: tasks.filter((t) => t.status === "COMPLETED").length,
    inProgress: tasks.filter((t) => t.status === "IN_PROGRESS").length,
  };

  return `
    <div class="issue-detail-container">
      <div class="issue-detail-header">
        <a href="/" class="back-link">← Back to Issues</a>
        <h2>Issue #${issue.number}</h2>
      </div>

      <div class="issue-title-section">
        <h1>${escapeHtml(issue.title)}</h1>
        <div class="issue-badges">
          ${renderTypeBadge(issue.type)}
          ${renderPriorityBadge(issue.priority)}
          ${renderStatusBadge(issue.status)}
        </div>
      </div>

      <div class="tabs-container">
        <div class="tabs-nav">
          <a href="/issues/${issue.number}?tab=details" class="tab-link ${activeTab === "details" ? "active" : ""}">Details</a>
          <a href="/issues/${issue.number}?tab=plan" class="tab-link ${activeTab === "plan" ? "active" : ""}">
            Plan
            ${plan ? '<span class="tab-indicator tab-indicator-success"></span>' : ""}
          </a>
          <a href="/issues/${issue.number}?tab=tasks" class="tab-link ${activeTab === "tasks" ? "active" : ""}">
            Tasks
            ${tasks.length > 0 ? `<span class="tab-badge">${taskCounts.completed}/${taskCounts.total}</span>` : ""}
          </a>
          ${tasks.length > 0 ? `<a href="/board?issue=${issue.number}" class="tab-link tab-link-external">Board →</a>` : ""}
        </div>

        <div class="tab-content">
          ${activeTab === "details" ? renderDetailsTab(issue) : ""}
          ${activeTab === "plan" ? renderPlanTab(plan) : ""}
          ${activeTab === "tasks" ? renderTasksTab(tasks, issue.number) : ""}
        </div>
      </div>
    </div>
  `;
}

function renderDetailsTab(issue: Issue): string {
  return `
    <div class="tab-panel">
      <div class="issue-section">
        <h3>Description</h3>
        <div class="issue-description">
          ${escapeHtml(issue.description).replace(/\n/g, "<br>")}
        </div>
      </div>

      ${issue.acceptanceCriteria.length > 0 ? renderAcceptanceCriteria(issue.acceptanceCriteria) : ""}

      ${issue.labels.length > 0 ? renderLabelsSection(issue.labels) : ""}

      <div class="issue-metadata">
        <div class="metadata-row">
          <span class="metadata-label">Created:</span>
          <span class="metadata-value">${formatDate(issue.createdAt)}</span>
        </div>
        <div class="metadata-row">
          <span class="metadata-label">Updated:</span>
          <span class="metadata-value">${formatDate(issue.updatedAt)}</span>
        </div>
        ${issue.createdBy ? `
          <div class="metadata-row">
            <span class="metadata-label">Created By:</span>
            <span class="metadata-value">${escapeHtml(issue.createdBy)}</span>
          </div>
        ` : ""}
        ${issue.templateUsed ? `
          <div class="metadata-row">
            <span class="metadata-label">Template:</span>
            <span class="metadata-value">${escapeHtml(issue.templateUsed)}</span>
          </div>
        ` : ""}
      </div>
    </div>
  `;
}

function renderPlanTab(plan?: Plan): string {
  if (!plan) {
    return `
      <div class="tab-panel">
        <div class="empty-tab-state">
          <h3>No Implementation Plan</h3>
          <p>No implementation plan has been generated yet.</p>
          <p class="hint">Use the MCP tool <code>generate_plan</code> to create a plan for this issue.</p>
        </div>
      </div>
    `;
  }

  return `
    <div class="tab-panel">
      <div class="plan-header-row">
        <span class="badge badge-complexity badge-${plan.estimatedComplexity.toLowerCase()}">${plan.estimatedComplexity} Complexity</span>
      </div>

      <div class="issue-section">
        <h3>Summary</h3>
        <div class="plan-summary-content">
          ${escapeHtml(plan.summary)}
        </div>
      </div>

      <div class="issue-section">
        <h3>Approach</h3>
        <div class="approach-content">
          ${escapeHtml(plan.approach).replace(/\n/g, "<br>")}
        </div>
      </div>

      <div class="plan-metadata">
        <span class="plan-generated-by">Generated by: ${escapeHtml(plan.generatedBy)}</span>
        <span class="plan-date">on ${formatDate(plan.createdAt)}</span>
      </div>
    </div>
  `;
}

function renderTasksTab(tasks: Task[], issueNumber: number): string {
  if (tasks.length === 0) {
    return `
      <div class="tab-panel">
        <div class="empty-tab-state">
          <h3>No Tasks</h3>
          <p>No tasks have been created for this issue.</p>
          <p class="hint">Generate an implementation plan to create tasks.</p>
        </div>
      </div>
    `;
  }

  const completedTasks = tasks.filter((t) => t.status === "COMPLETED").length;
  const totalTasks = tasks.length;
  const progressPercent = Math.round((completedTasks / totalTasks) * 100);

  return `
    <div class="tab-panel">
      <div class="tasks-header-row">
        <div class="tasks-progress">
          <span class="progress-text">${completedTasks}/${totalTasks} completed</span>
          <div class="progress-bar">
            <div class="progress-fill" style="width: ${progressPercent}%"></div>
          </div>
        </div>
        <a href="/board?issue=${issueNumber}" class="btn btn-small">View on Board →</a>
      </div>

      <ul class="tasks-list">
        ${tasks.map((task) => renderTaskItem(task)).join("\n")}
      </ul>
    </div>
  `;
}

function renderTypeBadge(type: string): string {
  return `<span class="badge badge-type badge-${type.toLowerCase()}">${type}</span>`;
}

function renderPriorityBadge(priority: string): string {
  return `<span class="badge badge-priority badge-${priority.toLowerCase()}">${priority}</span>`;
}

function renderStatusBadge(status: string): string {
  const statusClass = status.toLowerCase().replace("_", "-");
  return `<span class="badge badge-status badge-${statusClass}">${status.replace("_", " ")}</span>`;
}

function renderAcceptanceCriteria(criteria: string[]): string {
  return `
    <div class="issue-section">
      <h3>Acceptance Criteria</h3>
      <ul class="acceptance-criteria">
        ${criteria.map((criterion) => `
          <li>
            <label class="criterion-item">
              <input type="checkbox" disabled>
              <span>${escapeHtml(criterion)}</span>
            </label>
          </li>
        `).join("\n")}
      </ul>
    </div>
  `;
}

function renderLabelsSection(labels: string[]): string {
  return `
    <div class="issue-section">
      <h3>Labels</h3>
      <div class="labels-list">
        ${labels.map((label) => `<span class="badge badge-label">${escapeHtml(label)}</span>`).join(" ")}
      </div>
    </div>
  `;
}

function formatDate(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function renderTaskItem(task: Task): string {
  const statusClass = task.status.toLowerCase().replace("_", "-");
  const statusIcon = getTaskStatusIcon(task.status);

  return `
    <li class="task-item task-${statusClass}">
      <div class="task-status-icon">${statusIcon}</div>
      <div class="task-content">
        <div class="task-title">${escapeHtml(task.title)}</div>
        <div class="task-description">${escapeHtml(task.description)}</div>
        ${task.acceptanceCriteria.length > 0 ? renderTaskCriteria(task.acceptanceCriteria) : ""}
      </div>
      <div class="task-meta">
        <span class="badge badge-task-status badge-${statusClass}">${task.status.replace("_", " ")}</span>
        ${task.estimatedMinutes ? `<span class="task-estimate">${task.estimatedMinutes}m</span>` : ""}
      </div>
    </li>
  `;
}

function getTaskStatusIcon(status: string): string {
  switch (status) {
    case "COMPLETED":
      return "✓";
    case "IN_PROGRESS":
      return "→";
    case "ABANDONED":
      return "✗";
    default:
      return "○";
  }
}

function renderTaskCriteria(criteria: string[]): string {
  return `
    <ul class="task-criteria">
      ${criteria.map((c) => `<li>${escapeHtml(c)}</li>`).join("\n")}
    </ul>
  `;
}
